src/main/java/com/rachidj/entities/Article.java
package com.rachidj.entities;

import lombok.Data;

import javax.persistence.*;

@Data
@Entity
@Table(name = "t_articles")
@NamedQuery(name = "articles.countAll", query = "SELECT COUNT(a) FROM Article a")
public class Article {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long idArticle;
    private String description;
    private String brand;

    @Column(name = "unitaryPrice")
    private double price;

    public Article(String description, String brand, double price) {
        this.description = description;
        this.brand = brand;
        this.price = price;
    }

    public Article() {
    }

    @Override
    public String toString() {
        return "Article{" +
                "idArticle=" + idArticle +
                ", description='" + description + '\'' +
                ", brand='" + brand + '\'' +
                ", price=" + price +
                '}';
    }
}

src/main/java/com/rachidj/entities/Command.java
package com.rachidj.entities;

import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.List;

@Entity
@Table(name = "t_commands")
public class Command {

    @Id @Getter @Setter
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long idCommand;

    @Getter @Setter
    @ManyToOne(targetEntity = User.class)
    @JoinColumn(name = "idUser", nullable = false)
    private User user;

    @Getter @Setter
    @Column(name = "commandDate")
    private String date;

    @Getter @Setter
    @OneToMany(targetEntity = CommandLine.class,
            mappedBy = "command",
            cascade = CascadeType.ALL)
    private List<CommandLine> lines = new ArrayList<>();

    public Command(User user, String date) {
        this.user = user;
        this.date = date;
    }

    public Command() {
    }

    @Override
    public String toString() {
        return "Command{" +
                "idCommand=" + idCommand +
                ", user=" + user +
                ", date='" + date + '\'' +
                ", commands=" + lines.size() +
                '}';
    }
}

src/main/java/com/rachidj/entities/CommandLine.java
package com.rachidj.entities;

import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;

@Entity
@Table(name = "t_commandlines")
public class CommandLine {

    @Id @Getter
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long idCommandLine;

    @Getter @Setter
    @ManyToOne(targetEntity = Command.class)
    @JoinColumn(name = "idCommand", nullable = false)
    private Command command;

    @Getter @Setter
    @ManyToOne(targetEntity = Article.class)
    @JoinColumn(name = "idArticle", nullable = false)
    private Article article;

    @Getter @Setter
    private int quantity;


    public CommandLine(Article article, int quantity) {
        this.article = article;
        this.quantity = quantity;
    }

    public CommandLine(Command command, Article article, int quantity) {
        this.command = command;
        this.article = article;
        this.quantity = quantity;
    }

    public CommandLine() {
    }

    public void increaseQuantity() {
        this.quantity++;
    }

    @Override
    public String toString() {
        return "CommandLine{" +
                "idCommandLine=" + idCommandLine +
                ", idCommand=" + command +
                ", article=" + article +
                ", quantity=" + quantity +
                '}';
    }
}

src/main/java/com/rachidj/entities/User.java
package com.rachidj.entities;

import lombok.Data;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.List;

@Data
@Entity
@Table(name = "t_users")
public class User {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long idUser;

    @Column(name = "login")
    private String username;
    private String password;
    private int connectionNumber = 0;

    // relation oneToOne avec l'entite UserInformation
    @OneToOne(cascade = CascadeType.ALL)
    @JoinColumn(name = "idInformations", nullable = false)
    private UserInformations userInformations;

    // relation oneToMany avec l'entite Command
    @OneToMany(mappedBy = "user")
    private List<Command> commands = new ArrayList<>();

    public User(String username, String password) {
        this.username = username;
        this.password = password;
    }

    public User(String username, String password, int connectionNumber, UserInformations userInformations) {
        this.username = username;
        this.password = password;
        this.connectionNumber = connectionNumber;
        this.userInformations = userInformations;
    }

    public User() {
    }

    @Override
    public String toString() {
        return "User{" +
                "idUser=" + idUser +
                ", username='" + username + '\'' +
                ", password='" + password + '\'' +
                ", connectionNumber=" + connectionNumber +
                ",\n userInformations=" + userInformations +
                ",\n commands=" + commands.size() +
                '}';
    }
}

src/main/java/com/rachidj/entities/UserInformations.java
package com.rachidj.entities;

import lombok.Data;

import javax.persistence.*;
import javax.validation.constraints.Email;

@Data
@Entity
@Table(name = "t_userinformations")
public class UserInformations {

    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long idInformations;
    private String address;
    private String city;
    @Email
    private String email;
    private String phoneNumber;

    @OneToOne(targetEntity = User.class)
    @JoinColumn(name = "idInformations")
    private User user;

    public UserInformations(String address, String city, @Email String email, String phoneNumber) {
        this.address = address;
        this.city = city;
        this.email = email;
        this.phoneNumber = phoneNumber;
    }

    public UserInformations() {
    }

    @Override
    public String toString() {
        return "UserInformations{" +
                "idInformations=" + idInformations +
                ", address='" + address + '\'' +
                ", city='" + city + '\'' +
                ", email='" + email + '\'' +
                ", phoneNumber='" + phoneNumber + '\'' +
                '}';
    }
}

src/main/java/com/rachidj/models/CatalogBrowser.java
package com.rachidj.models;

import com.rachidj.dao.DAOFactory;
import com.rachidj.entities.Article;
import com.rachidj.entities.CommandLine;
import lombok.Getter;

import java.util.ArrayList;
import java.util.List;

public class CatalogBrowser {
    private Long currentPosition = 1L;

    @Getter
    private Article currentArticle;
    private Long articlesCount = DAOFactory.articleDAO().getCount();
    @Getter
    private List<CommandLine> shoppingCart = new ArrayList<>();

    public CatalogBrowser() {
        currentArticle = DAOFactory.articleDAO().read(currentPosition);
    }

    public int getShoppingCartSize() {
        int fullQuantity = 0;
        for(CommandLine line: shoppingCart) {
            fullQuantity += line.getQuantity();
        }

        return fullQuantity;
    }

    public void goPrevious() {
        if(--currentPosition < 1){
            currentPosition = articlesCount;
        }
        currentArticle = DAOFactory.articleDAO().read(currentPosition);
    }

    public void goNext() {
        if(++currentPosition > articlesCount) {
            currentPosition = 1L;
        }
        currentArticle = DAOFactory.articleDAO().read(currentPosition);
    }

    public void addToCart() {
        for(CommandLine line: shoppingCart){
            if(line.getArticle().getIdArticle() == currentArticle.getIdArticle()){
                line.increaseQuantity();
                return;
            }
        }
        shoppingCart.add(new CommandLine(currentArticle, 1));
    }
}

src/main/java/com/rachidj/models/ShoppingCartLine.java
package com.rachidj.models;


import com.rachidj.entities.Article;
import lombok.Getter;
import lombok.NonNull;
import lombok.Setter;

import java.util.Optional;

public class ShoppingCartLine {

    @Getter @Setter @NonNull
    private Article article;

    @Getter @Setter
    private int quantity;

    public ShoppingCartLine(Article article, int quantity) {
        this.article = article;
        this.quantity = quantity;
    }

    public ShoppingCartLine() {
    }

    public void increaseQuantity() {
        this.quantity++;
    }
}

src/main/java/com/rachidj/webstoreJPA/HelloServlet.java
package com.rachidj.webstoreJPA;

import java.io.*;
import javax.servlet.http.*;
import javax.servlet.annotation.*;

@WebServlet(name = "helloServlet", value = "/hello-servlet")
public class HelloServlet extends HttpServlet {
    private String message;

    public void init() {
        message = "Hello World!";
    }

    public void doGet(HttpServletRequest request, HttpServletResponse response) throws IOException {
        response.setContentType("text/html");

        // Hello
        PrintWriter out = response.getWriter();
        out.println("<html><body>");
        out.println("<h1>" + message + "</h1>");
        out.println("</body></html>");
    }

    public void destroy() {
    }
}

src/main/webapp/index.jsp
<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<!DOCTYPE html>
<html>
<head>
    <title>JSP - Hello World</title>
</head>
<body>
<h1><%= "Hello World!" %>
</h1>
<br/>
<a href="login">Login</a>
</body>
</html>

src/main/webapp/login.jsp
<%--
  Created by IntelliJ IDEA.
  User: rachidj
  Date: 13/03/2021
  Time: 14:55
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <title>Login</title>
</head>
<body>
<h1>Login Screen</h1>
<form method="post" action="login">
    Login: <input name="txtLogin" value="${login}" autofocus>
    <br/>
    Password: <input name="txtPassword"  type="password" value="${password}">
    <br/>
    <input type="submit" value="Connect">
</form>
</body>
</html>

src/main/webapp/myCart.jsp
<%--
  Created by IntelliJ IDEA.
  User: rachidj
  Date: 14/03/2021
  Time: 19:32
  To change this template use File | Settings | File Templates.
--%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>

<html>
<head>
    <title>Shopping Cart Summary | ${connectedUser.username}</title>
</head>
<body>
    <table border="1">
        <thead>
        <tr>
            <th>Identifier</th>
            <th>Description</th>
            <th>Brand</th>
            <th>Unitary Price</th>
            <th>Quantity</th>
            <th>Sub-Total</th>
        </tr>
        </thead>
        <tbody>
        <c:set var="totalOrder" value="${0}"/>
        <c:forEach items="${catalogBrowser.shoppingCart}" var="line">
            <tr>
                <td>${line.article.idArticle}</td>
                <td>${line.article.description}</td>
                <td>${line.article.brand}</td>
                <td>${line.article.price}</td>
                <td>${line.quantity}</td>
                <td><fmt:formatNumber
                        type="number"
                        maxFractionDigits="2"
                        value="${line.article.price * line.quantity}"/></td>
            </tr>
            <c:set var="totalOrder" value="${totalOrder + (line.article.price * line.quantity)}"/>
        </c:forEach>
        </tbody>
    </table>
    <br/>
    <br/>
    <h3>Total order :   ${totalOrder}</h3>
    <form method="post" action="myCart">
        <input type="submit" name="btnBuy" value="Buy now">
    </form>
    <p>${orderMessage}</p>
</body>
</html>

src/main/webapp/userInformations.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%--
  Created by IntelliJ IDEA.
  User: rachidj
  Date: 13/03/2021
  Time: 16:16
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <title>Title</title>
</head>
<body>
    <h3>My informations</h3><br/>
    Login:          ${connectedUser.username}<br/>
    Address:        ${connectedUser.userInformations.address}<br/>
    City:           ${connectedUser.userInformations.city}<br/>
    <br/>
    Email:          ${connectedUser.userInformations.email}<br/>
    Phone Number:   ${connectedUser.userInformations.phoneNumber}<br/>

    <br/>
    <h3>Historique des achats:</h3><br/>
    <c:forEach items="${connectedUser.commands}" var="command">
        ${command.date}
    </c:forEach>
</body>
</html>

src/main/webapp/viewArticles.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <title>All articles</title>
</head>
<body>
    <h3> View Article - <a href="userInformations">${connectedUser.username}</a></h3>
    <br/>
        Identifier: ${catalogBrowser.currentArticle.idArticle}<br/>
        Brand: ${catalogBrowser.currentArticle.brand}<br/>
        Description: ${catalogBrowser.currentArticle.description}<br/>
        Unit Price: ${catalogBrowser.currentArticle.price}<br/>
    <br/>
    <form action="viewArticles" method="post">
        <input name="btnPrevious" type="submit" value="Previous">
        &nbsp; &nbsp;
        <input name="btnAdd" type="submit" value="Add to cart">
        &nbsp; &nbsp;
        <input name="btnNext" type="submit" value="Next">
    </form>
    <br/>
    <p>${catalogBrowser.shoppingCartSize}
        article<c:if test="${catalogBrowser.shoppingCartSize gt 1}">s</c:if> in the <a href="myCart">cart</a></p>
    <form action="editArticle" method="get">
        <input name="btnEdit" type="submit" value="Edit">
    </form>
</body>
</html>